---
name: "Setup Linux Build Environment"
description: "Configures Flutter and dependencies for Linux builds"

inputs:
  gpg-key:
    description: "Base64-encoded GPG private key"
    required: false
  gpg-key-id:
    description: "GPG key ID for signing"
    required: false

runs:
  using: "composite"
  steps:
    - name: Install system dependencies
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y ninja-build libgtk-3-dev libblkid-dev \
        liblzma-dev libsecret-1-dev libjsoncpp-dev libsqlite3-dev \
        libxdg-basedir-dev cmake pkg-config clang git xz-utils zip \
        libglu1-mesa curl libstdc++-12-dev

    - name: Install Linux build dependencies
      shell: bash
      run: |
        flutter pub get --enforce-lockfile
        flutter doctor

    - name: Setup Linux code signing
      if: inputs.gpg-key != '' && 'KomodoPlatform/komodo-wallet' == github.repository
      shell: bash
      run: |
        echo "${{ inputs.gpg-key }}" | base64 --decode | gpg --import --batch --yes
        mkdir -p ~/.gnupg
        echo "allow-preset-passphrase" > ~/.gnupg/gpg-agent.conf
        gpg-connect-agent reloadagent /bye
        echo "DEBSIGN_KEYID=${{ inputs.gpg-key-id }}" > ~/.devscripts
