name: "Code Coverage"
description: "Generates and uploads code coverage report"
inputs:
  test_file:
    description: "The test file to run"
    required: false
    default: "test_units/main.dart"
runs:
  using: "composite"
  steps:
    - name: Code Coverage
      continue-on-error: false
      shell: bash
      run: |
        echo "Running code coverage"
        if [ "$RUNNER_OS" == "Linux" ]; then
          echo "Installing lcov..."
          sudo apt-get update -qq -y 2>&1 > /dev/null
          sudo apt-get install lcov -y 2>&1 > /dev/null
          echo "lcov has been successfully installed."
        elif [ "$RUNNER_OS" == "macOS" ]; then
          if ! command -v brew &> /dev/null; then
              echo "Homebrew is not installed. Installing Homebrew..."
              /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
              # Check if installation was successful
              if [ $? -eq 0 ]; then
                  echo "Homebrew has been successfully installed."
              else
                  echo "Failed to install Homebrew. Please check the error messages above and try again."
                  exit 1
              fi
          fi

          brew install lcov
        else
           echo "Unsupported operating system"
           exit 1
        fi
        flutter test --coverage ${{ inputs.test_file }} 2>&1 > /dev/null && \
          echo "Generated code coverage report" || \
          echo "ERROR: Failed to generate code coverage report"

        echo "Generating HTML report from lcov.info..."
        genhtml -q coverage/lcov.info -o coverage/html && \
          echo "Generated code coverage report" || \
          echo "ERROR: Failed to generate code coverage report"

        zip -q -r coverage-html.zip coverage/html && \
          echo "Created coverage-html.zip" || \
          echo "ERROR: Failed to compress coverage/html into a ZIP archive"
        echo "Done running code coverage"

    - name: Upload Code Coverage Report
      uses: actions/upload-artifact@v4
      with:
        name: ${{ runner.os }}-lcov.info
        path: ./coverage/lcov.info

    - name: Upload Code Coverage HTML Report
      uses: actions/upload-artifact@v4
      with:
        name: ${{ runner.os }}-coverage-html
        path: ./coverage-html.zip
